#
# Copyright (c) 2025, 2026 Oracle and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Validate"

on:
  pull_request:
#  push:
#    branches-ignore: [ 'main', 'release-*' ]
#    tags-ignore: [ '**' ]
  workflow_call:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout
        required: false
        type: string
        default: ''

env:
  MVN_VERSION: 3.9.9
  JAVA_VERSION: 21
  JAVA_DISTRO: oracle
  MVN_ARGS: |
    -B -fae -e
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=60
    -Dmaven.wagon.http.retryHandler.count=3
    -Djdk.toolchain.version=${JAVA_VERSION}
    -Dcache.enabled=true

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prime-build:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
      - name: Helidon Priming build
        uses: ./.github/actions/common
        with:
          free-space: true
          build-cache: read-write
          maven-cache: read-write
          run: |
            etc/scripts/prime-build.sh
  copyright:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
      - uses: ./.github/actions/common
        with:
          run: etc/scripts/copyright.sh
  checkstyle:
    needs: [ prime-build ]
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: ./.github/actions/common
        with:
          run: etc/scripts/checkstyle.sh
  shellcheck:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: ./.github/actions/common
        with:
          maven-cache: none
          run: etc/scripts/shellcheck.sh
  neo4j:
    needs: [ prime-build ]
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022 ]
        include:
          - { os: ubuntu-22.04, platform: linux }
          - { os: windows-2022, platform: windows }
    runs-on: ${{ matrix.os }}
    name: neo4j/${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: ./.github/actions/common
        with:
          build-cache: read-only
          maven-cache: read-only
          test-artifact-name: neo4j-${{ matrix.platform }}
          free-space: true
          run: |
            mvn --version
            mvn ${MVN_ARGS} build-cache:go-offline
            mvn ${MVN_ARGS} \
              -Dorg.slf4j.simpleLogger.showThreadName=true \
              -Dsurefire.reportNameSuffix=${{ matrix.platform }} \
              -pl neo4j \
              -am \
              -amd \
              -Pexamples,tests,spotbugs,javadoc \
              verify
  hashicorp_vault:
    needs: [ prime-build ]
    timeout-minutes: 45
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022 ]
        include:
          - { os: ubuntu-22.04, platform: linux }
          - { os: windows-2022, platform: windows }
    runs-on: ${{ matrix.os }}
    name: hashicorp-vault/${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: ./.github/actions/common
        with:
          build-cache: read-only
          maven-cache: read-only
          test-artifact-name: hashicorp-vault-${{ matrix.platform }}
          free-space: true
          run: |
            mvn --version
            mvn ${MVN_ARGS} build-cache:go-offline
            mvn ${MVN_ARGS} \
              -Dorg.slf4j.simpleLogger.showThreadName=true \
              -Dsurefire.reportNameSuffix=${{ matrix.platform }} \
              -pl hashicorp-vault \
              -am \
              -amd \
              -Pexamples,tests,spotbugs,javadoc \
              verify
  oci_v3:
    needs: [ prime-build ]
    timeout-minutes: 45
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022 ]
        include:
          - { os: ubuntu-22.04, platform: linux }
          - { os: windows-2022, platform: windows }
    runs-on: ${{ matrix.os }}
    name: oci-v3/${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: ./.github/actions/common
        with:
          build-cache: read-only
          maven-cache: read-only
          test-artifact-name: oci-v3-${{ matrix.platform }}
          free-space: true
          run: |
            mvn --version
            mvn ${MVN_ARGS} build-cache:go-offline
            mvn ${MVN_ARGS} \
              -Dorg.slf4j.simpleLogger.showThreadName=true \
              -Dsurefire.reportNameSuffix=${{ matrix.platform }} \
              -pl oci-v3 \
              -am \
              -amd \
              -Pexamples,tests,spotbugs,javadoc \
              verify
  langchain4j:
    needs: [ prime-build ]
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022 ]
        include:
          - { os: ubuntu-22.04, platform: linux }
          - { os: windows-2022, platform: windows }
    runs-on: ${{ matrix.os }}
    name: langchain4j/${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: ./.github/actions/common
        with:
          build-cache: read-only
          maven-cache: read-only
          test-artifact-name: langchain4j-${{ matrix.platform }}
          free-space: true
          run: |
            mvn --version
            mvn ${MVN_ARGS} io.helidon.build-tools:helidon-build-cache-maven-plugin:4.0.26:go-offline
            mvn ${MVN_ARGS} \
              -Dorg.slf4j.simpleLogger.showThreadName=true \
              -Dsurefire.reportNameSuffix=${{ matrix.platform }} \
              -pl langchain4j \
              -am \
              -amd \
              -Pexamples,tests,spotbugs,javadoc \
              verify
  eureka:
    needs: [ prime-build ]
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022 ]
        include:
          - { os: ubuntu-22.04, platform: linux }
          - { os: windows-2022, platform: windows }
    runs-on: ${{ matrix.os }}
    name: eureka/${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: ./.github/actions/common
        with:
          build-cache: read-only
          maven-cache: read-only
          test-artifact-name: eureka-${{ matrix.platform }}
          free-space: true
          run: |
            mvn --version
            mvn ${MVN_ARGS} build-cache:go-offline
            mvn ${MVN_ARGS} \
              -Dorg.slf4j.simpleLogger.showThreadName=true \
              -Dsurefire.reportNameSuffix=${{ matrix.platform }} \
              -pl eureka \
              -am \
              -amd \
              -Pexamples,tests,spotbugs,javadoc \
              verify
  gate:
    runs-on: ubuntu-22.04
    needs: [ prime-build, copyright, checkstyle, shellcheck, neo4j, langchain4j, hashicorp_vault, oci_v3 ]
    steps:
      - shell: bash
        run: |
          echo OK

